= Modernize your Java EE applications with JBoss EAP 7 - Red Hat Summit 2016 Lab
Thomas Qvarnstrom <tqvarnst@redhat.com>; Marc Zottner <mzottner@redhat.com>

:sectnums!:
:toc: left
:revnumber: 0.5
:revdate: 2016-06-27

This repository is the used to develop the 2016 Red Hat Summit lab for JBoss EAP 7. The main authors of _{doctitle}_ is *{author}*, Red Hat and *{author_2}*, Red Hat and the current version ({revnumber}) was last updated on {revdate}.

== Lab Overview

[cols="1,4", options="header"]
|===
2+|  Details
| Technology/Product | Red Hat JBoss Enterprise Application Platform 7
| Difficulty | 2
| Time | 2 hours
| Prerequisites | An understanding of Java EE application development
|===


== Introduction

This is a self-paced lab, aimed at developers using, or wanting to use, Red Hat JBoss Enterprise Application Platform 7.

The lab consists of several exercises walking the participant through basic and new features of Red Hat JBoss EAP 7.

Here is a short list for the available exercises:

* link:exercise1-setup.adoc[Exercise 1 - Environment setup]
* link:exercise2-frontend.adoc[Exercise 2 - Java EE 7 Front-end technologies]
* link:exercise3-batch.adoc[Exercise 3 - Batch Applications]
* link:exercise4-messaging.adoc[Exercise 4 - Messaging with Artemis]
* link:exercise5-concurrency.adoc[Exercise 5 - Java EE Concurrency Utilities]
* link:exercise6-high-availability.adoc[Exercise 6 - High availability]
