= Modernize your Java EE applications with JBoss EAP 7 - Red Hat Middleware Workshop
Thomas Qvarnstrom <tqvarnst@redhat.com>; Marc Zottner <mzottner@redhat.com>; James Falkner <jfalkner@redhat.com>

:sectnums!:
:toc: left
:revnumber: 0.6
:revdate: 2016-07-15

This repository is the used to develop the a workshop for modernizing apps with JBoss EAP 7 and Java EE 7. The main authors of _{doctitle}_ are *{author}*, Red Hat, *{author_2}* and *{author_3}*, Red Hat and the current version ({revnumber}) was last updated on {revdate}.

== Workshop Overview

[cols="1,4", options="header"]
|===
2+|  Details
| Technology/Product | Red Hat JBoss Enterprise Application Platform 7
| Difficulty | 2
| Time | 2 hours
| Prerequisites | An understanding of Java EE application development
|===


== Introduction

This workshop can be a self-paced or instructor-led hands-on workshop, aimed at developers using, or wanting to use, Red Hat JBoss Enterprise Application Platform 7.

The workshop consists of several exercises walking the participant through basic and new features of Red Hat JBoss EAP 7.

Here is a short list for the available exercises:

* link:exercise1-setup.adoc[Exercise 1 - Environment setup]
* link:exercise2-frontend.adoc[Exercise 2 - Java EE 7 Front-end technologies]
* link:exercise3-batch.adoc[Exercise 3 - Batch Applications]
* link:exercise4-messaging.adoc[Exercise 4 - Messaging with Artemis]
* link:exercise5-concurrency.adoc[Exercise 5 - Java EE Concurrency Utilities]
* link:exercise6-high-availability.adoc[Exercise 6 - High availability]
